import type { CatalogEntry } from './types';

/**
 * 資料驅動的物件目錄。新增物件（包含未來的 GLB 素材包）只需要在此新增一筆資料，
 * 不需要更動任何互動/UI 程式碼——見 objects/ObjectFactory.ts 的 procedural/gltf 分派邏輯。
 */
export const catalogData: CatalogEntry[] = [
  {
    id: 'person_generic',
    category: 'person',
    label: '人',
    keywords: ['人', '人物', 'person', 'human'],
    icon: '🧍',
    visualSource: { type: 'procedural', builderKey: 'person' },
  },
  {
    id: 'plant_tree',
    category: 'plant',
    label: '樹',
    keywords: ['樹', '闊葉樹', 'tree'],
    icon: '🌳',
    visualSource: { type: 'procedural', builderKey: 'tree' },
  },
  {
    id: 'plant_pine',
    category: 'plant',
    label: '松樹',
    keywords: ['松', '松樹', 'pine'],
    icon: '🌲',
    visualSource: { type: 'procedural', builderKey: 'pine' },
  },
  {
    id: 'building_house',
    category: 'building',
    label: '房屋',
    keywords: ['房屋', '房子', '家', 'house'],
    icon: '🏠',
    visualSource: { type: 'procedural', builderKey: 'house' },
  },
  {
    id: 'natural_rock',
    category: 'natural',
    label: '岩石',
    keywords: ['岩石', '石頭', 'rock', 'stone'],
    icon: '🪨',
    visualSource: { type: 'procedural', builderKey: 'rock' },
  },
  {
    id: 'vehicle_boat',
    category: 'vehicle',
    label: '小船',
    keywords: ['船', '小船', '帆船', 'boat'],
    icon: '⛵',
    visualSource: { type: 'procedural', builderKey: 'boat' },
  },
  {
    id: 'demo_gltf_tree',
    category: 'plant',
    label: '（示範）GLTF 樹',
    keywords: ['示範', 'demo', 'gltf'],
    icon: '🌴',
    // 刻意指向一個不存在的檔案：用來驗證「載入失敗→優雅降級為佔位符」這條路徑。
    // 之後接上真實的 Quaternius／Kenney 等 CC0 素材包時，只要把 url 換成實際檔案即可。
    visualSource: { type: 'gltf', url: 'assets/models/placeholder/tree-demo.glb' },
  },

  // 動物
  {
    id: 'animal_snake',
    category: 'animal',
    label: '蛇',
    keywords: ['蛇', 'snake'],
    icon: '🐍',
    visualSource: { type: 'procedural', builderKey: 'snake' },
  },
  {
    id: 'animal_bird',
    category: 'animal',
    label: '鳥',
    keywords: ['鳥', '小鳥', 'bird'],
    icon: '🐦',
    visualSource: { type: 'procedural', builderKey: 'bird' },
  },
  {
    id: 'animal_horse',
    category: 'animal',
    label: '馬',
    keywords: ['馬', 'horse'],
    icon: '🐴',
    visualSource: { type: 'procedural', builderKey: 'horse' },
  },
  {
    id: 'animal_turtle',
    category: 'animal',
    label: '烏龜',
    keywords: ['烏龜', '龜', 'turtle'],
    icon: '🐢',
    visualSource: { type: 'procedural', builderKey: 'turtle' },
  },

  // 宗教／神話
  {
    id: 'religious_cross',
    category: 'religious_mythical',
    label: '十字架',
    keywords: ['十字架', '十字', 'cross'],
    icon: '✝️',
    visualSource: { type: 'procedural', builderKey: 'cross' },
  },
  {
    id: 'religious_stupa',
    category: 'religious_mythical',
    label: '佛塔',
    keywords: ['佛塔', '寶塔', '佛', 'stupa', 'pagoda'],
    icon: '🛕',
    visualSource: { type: 'procedural', builderKey: 'stupa' },
  },
  {
    id: 'religious_candle',
    category: 'religious_mythical',
    label: '蠟燭',
    keywords: ['蠟燭', '燭', 'candle'],
    icon: '🕯️',
    visualSource: { type: 'procedural', builderKey: 'candle' },
  },

  // 幻想生物
  {
    id: 'fantasy_mushroom_house',
    category: 'fantasy',
    label: '蘑菇屋',
    keywords: ['蘑菇屋', '蘑菇', '香菇', 'mushroom'],
    icon: '🍄',
    visualSource: { type: 'procedural', builderKey: 'mushroomHouse' },
  },
  {
    id: 'fantasy_crystal',
    category: 'fantasy',
    label: '魔法水晶',
    keywords: ['水晶', '魔法水晶', 'crystal'],
    icon: '🔮',
    visualSource: { type: 'procedural', builderKey: 'crystal' },
  },

  // 植物
  {
    id: 'plant_flower',
    category: 'plant',
    label: '花',
    keywords: ['花', '花朵', 'flower'],
    icon: '🌸',
    visualSource: { type: 'procedural', builderKey: 'flower' },
  },

  // 建築
  {
    id: 'building_bridge',
    category: 'building',
    label: '橋',
    keywords: ['橋', '橋樑', 'bridge'],
    icon: '🌉',
    visualSource: { type: 'procedural', builderKey: 'bridge' },
  },

  // 交通工具
  {
    id: 'vehicle_car',
    category: 'vehicle',
    label: '汽車',
    keywords: ['汽車', '車', 'car'],
    icon: '🚗',
    visualSource: { type: 'procedural', builderKey: 'car' },
  },

  // ────────────────────────────────────────────────────────────
  // 以下為外部 GLB/GLTF 素材（CC0，來自 Kenney.nl 與 Quaternius）
  // ────────────────────────────────────────────────────────────
  {
    id: 'person_male_glb',
    category: 'person',
    label: '男人（模型）',
    keywords: ['男人', '男性', 'man'],
    icon: '👨',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-mini-characters/character-male-a.glb', scale: 2.2 },
  },
  {
    id: 'person_female_glb',
    category: 'person',
    label: '女人（模型）',
    keywords: ['女人', '女性', 'woman'],
    icon: '👩',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-mini-characters/character-female-a.glb', scale: 2.2 },
  },
  {
    id: 'animal_horse_glb',
    category: 'animal',
    label: '馬（模型）',
    keywords: ['馬', 'horse'],
    icon: '🐎',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/horse.gltf', scale: 2.5 },
  },
  {
    id: 'animal_fox_glb',
    category: 'animal',
    label: '狐狸',
    keywords: ['狐狸', 'fox'],
    icon: '🦊',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/fox.gltf', scale: 2.5 },
  },
  {
    id: 'animal_wolf_glb',
    category: 'animal',
    label: '狼',
    keywords: ['狼', 'wolf'],
    icon: '🐺',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/wolf.gltf', scale: 2.5 },
  },
  {
    id: 'animal_deer_glb',
    category: 'animal',
    label: '鹿',
    keywords: ['鹿', 'deer'],
    icon: '🦌',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/deer.gltf', scale: 2.5 },
  },
  {
    id: 'animal_dog_glb',
    category: 'animal',
    label: '狗',
    keywords: ['狗', '犬', 'dog', 'husky'],
    icon: '🐕',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/husky.gltf', scale: 2.5 },
  },
  {
    id: 'plant_oak_glb',
    category: 'plant',
    label: '橡樹（模型）',
    keywords: ['橡樹', '樹', 'oak', 'tree'],
    icon: '🌳',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/tree_oak.glb', scale: 5 },
  },
  {
    id: 'plant_flower_glb',
    category: 'plant',
    label: '花（模型）',
    keywords: ['花', '花朵', 'flower'],
    icon: '🌺',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/flower_red.glb', scale: 3 },
  },
  {
    id: 'plant_mushroom_glb',
    category: 'plant',
    label: '蘑菇',
    keywords: ['蘑菇', '香菇', 'mushroom'],
    icon: '🍄',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/mushroom_red.glb', scale: 3 },
  },
  {
    id: 'natural_rock_large_glb',
    category: 'natural',
    label: '大岩石（模型）',
    keywords: ['岩石', '大石頭', 'rock', 'boulder'],
    icon: '🪨',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/rock_large.glb', scale: 4 },
  },
  {
    id: 'natural_rock_tall_glb',
    category: 'natural',
    label: '尖岩',
    keywords: ['岩石', '尖岩', 'rock', 'spire'],
    icon: '🗻',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/rock_tall.glb', scale: 4 },
  },
  {
    id: 'building_bridge_stone_glb',
    category: 'building',
    label: '石橋',
    keywords: ['橋', '石橋', 'bridge', 'stone'],
    icon: '🌉',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/bridge_stone.glb', scale: 3 },
  },
  {
    id: 'building_tent_glb',
    category: 'building',
    label: '帳篷',
    keywords: ['帳篷', '帳', 'tent'],
    icon: '⛺',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-survival/tent.glb', scale: 3 },
  },
  {
    id: 'vehicle_sailboat_glb',
    category: 'vehicle',
    label: '帆船（模型）',
    keywords: ['船', '帆船', 'boat', 'sail'],
    icon: '⛵',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-watercraft/boat-sail.glb', scale: 2.5 },
  },
  {
    id: 'vehicle_canoe_glb',
    category: 'vehicle',
    label: '獨木舟',
    keywords: ['獨木舟', '船', 'canoe'],
    icon: '🛶',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/canoe.glb', scale: 2.5 },
  },
  {
    id: 'religious_cross_glb',
    category: 'religious_mythical',
    label: '十字架（模型）',
    keywords: ['十字架', '十字', 'cross'],
    icon: '✝️',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/cross.glb', scale: 2.2 },
  },
  {
    id: 'religious_candle_glb',
    category: 'religious_mythical',
    label: '蠟燭（模型）',
    keywords: ['蠟燭', '燭', 'candle'],
    icon: '🕯️',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/candle.glb', scale: 2.2 },
  },
  {
    id: 'religious_altar_glb',
    category: 'religious_mythical',
    label: '石祭壇',
    keywords: ['祭壇', '石祭壇', 'altar'],
    icon: '⛩️',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/altar-stone.glb', scale: 2.2 },
  },
  {
    id: 'fantasy_ghost_glb',
    category: 'fantasy',
    label: '幽靈',
    keywords: ['幽靈', '鬼', 'ghost'],
    icon: '👻',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/character-ghost.glb', scale: 2.2 },
  },
  {
    id: 'fantasy_skeleton_glb',
    category: 'fantasy',
    label: '骷髏',
    keywords: ['骷髏', '骨骸', 'skeleton'],
    icon: '💀',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/character-skeleton.glb', scale: 2.2 },
  },
  {
    id: 'fantasy_orc_glb',
    category: 'fantasy',
    label: '半獸人',
    keywords: ['半獸人', '獸人', 'orc'],
    icon: '👹',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-mini-dungeon/character-orc.glb', scale: 2.2 },
  },
];
