import type { CatalogEntry } from './types';

/**
 * 資料驅動的物件目錄。新增物件（包含未來的 GLB 素材包）只需要在此新增一筆資料，
 * 不需要更動任何互動/UI 程式碼——見 objects/ObjectFactory.ts 的 procedural/gltf 分派邏輯。
 */
export const catalogData: CatalogEntry[] = [
  {
    id: 'plant_tree',
    category: 'plant',
    label: '樹',
    keywords: ['樹', '闊葉樹', 'tree'],
    icon: '🌳',
    visualSource: { type: 'procedural', builderKey: 'tree' },
  },
  {
    id: 'plant_pine',
    category: 'plant',
    label: '松樹',
    keywords: ['松', '松樹', 'pine'],
    icon: '🌲',
    visualSource: { type: 'procedural', builderKey: 'pine' },
  },
  {
    id: 'building_house',
    category: 'building',
    label: '房屋',
    keywords: ['房屋', '房子', '家', 'house'],
    icon: '🏠',
    visualSource: { type: 'procedural', builderKey: 'house' },
  },
  {
    id: 'natural_rock',
    category: 'natural',
    label: '岩石',
    keywords: ['岩石', '石頭', 'rock', 'stone'],
    icon: '🪨',
    visualSource: { type: 'procedural', builderKey: 'rock' },
  },
  {
    id: 'vehicle_boat',
    category: 'vehicle',
    label: '小船',
    keywords: ['船', '小船', '帆船', 'boat'],
    icon: '⛵',
    visualSource: { type: 'procedural', builderKey: 'boat' },
  },

  // 動物
  {
    id: 'animal_snake',
    category: 'animal_land',
    label: '蛇',
    keywords: ['蛇', 'snake'],
    icon: '🐍',
    visualSource: { type: 'procedural', builderKey: 'snake' },
  },
  {
    id: 'animal_bird',
    category: 'animal_land',
    label: '鳥',
    keywords: ['鳥', '小鳥', 'bird'],
    icon: '🐦',
    visualSource: { type: 'procedural', builderKey: 'bird' },
  },
  {
    id: 'animal_turtle',
    category: 'animal_water',
    label: '烏龜',
    keywords: ['烏龜', '龜', 'turtle'],
    icon: '🐢',
    visualSource: { type: 'procedural', builderKey: 'turtle' },
  },

  // 宗教／神話
  {
    id: 'religious_stupa',
    category: 'religious_mythical',
    label: '佛塔',
    keywords: ['佛塔', '寶塔', '佛', 'stupa', 'pagoda'],
    icon: '🛕',
    visualSource: { type: 'procedural', builderKey: 'stupa' },
  },

  // 幻想生物
  {
    id: 'fantasy_mushroom_house',
    category: 'fantasy',
    label: '蘑菇屋',
    keywords: ['蘑菇屋', '蘑菇', '香菇', 'mushroom'],
    icon: '🍄',
    visualSource: { type: 'procedural', builderKey: 'mushroomHouse' },
  },
  {
    id: 'fantasy_crystal',
    category: 'fantasy',
    label: '魔法水晶',
    keywords: ['水晶', '魔法水晶', 'crystal'],
    icon: '🔮',
    visualSource: { type: 'procedural', builderKey: 'crystal' },
  },

  // 植物

  // 建築
  {
    id: 'building_bridge',
    category: 'building',
    label: '橋',
    keywords: ['橋', '橋樑', 'bridge'],
    icon: '🌉',
    visualSource: { type: 'procedural', builderKey: 'bridge' },
  },

  // 交通工具
  {
    id: 'vehicle_car',
    category: 'vehicle',
    label: '汽車',
    keywords: ['汽車', '車', 'car'],
    icon: '🚗',
    visualSource: { type: 'procedural', builderKey: 'car' },
  },

  // ────────────────────────────────────────────────────────────
  // 以下為外部 GLB/GLTF 素材（CC0，來自 Kenney.nl 與 Quaternius）
  // ────────────────────────────────────────────────────────────
  {
    id: 'person_male_glb',
    category: 'person',
    label: '男人',
    keywords: ['男人', '男性', 'man'],
    icon: '👨',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/man-casual.glb', targetSize: 4.5 },
  },
  {
    id: 'person_female_glb',
    category: 'person',
    label: '女人',
    keywords: ['女人', '女性', 'woman'],
    icon: '👩',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/woman-casual.glb', targetSize: 4.5 },
  },
  {
    id: 'animal_horse_glb',
    category: 'animal_land',
    label: '馬',
    keywords: ['馬', 'horse'],
    icon: '🐎',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/horse.glb', targetSize: 5.5 },
  },
  {
    id: 'animal_fox_glb',
    category: 'animal_land',
    label: '狐狸',
    keywords: ['狐狸', 'fox'],
    icon: '🦊',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/fox.glb', targetSize: 3 },
  },
  {
    id: 'animal_wolf_glb',
    category: 'animal_land',
    label: '狼',
    keywords: ['狼', 'wolf'],
    icon: '🐺',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/wolf.glb', targetSize: 3.8 },
  },
  {
    id: 'animal_deer_glb',
    category: 'animal_land',
    label: '鹿',
    keywords: ['鹿', 'deer'],
    icon: '🦌',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/deer.glb', targetSize: 4.2 },
  },
  {
    id: 'animal_dog_glb',
    category: 'animal_land',
    label: '狗',
    keywords: ['狗', '犬', 'dog', 'husky'],
    icon: '🐕',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/husky.glb', targetSize: 3.5 },
  },
  {
    id: 'plant_oak_glb',
    category: 'plant',
    label: '橡樹',
    keywords: ['橡樹', '樹', 'oak', 'tree'],
    icon: '🌳',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/tree_oak.glb', targetSize: 8 },
  },
  {
    id: 'plant_flower_glb',
    category: 'plant',
    label: '花',
    keywords: ['花', '花朵', 'flower'],
    icon: '🌺',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/flower_red.glb', targetSize: 2.5 },
  },
  {
    id: 'plant_mushroom_glb',
    category: 'plant',
    label: '蘑菇',
    keywords: ['蘑菇', '香菇', 'mushroom'],
    icon: '🍄',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/mushroom_red.glb', targetSize: 2 },
  },
  {
    id: 'natural_rock_large_glb',
    category: 'natural',
    label: '大岩石',
    keywords: ['岩石', '大石頭', 'rock', 'boulder'],
    icon: '🪨',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/rock_large.glb', targetSize: 5 },
  },
  {
    id: 'natural_rock_tall_glb',
    category: 'natural',
    label: '尖岩',
    keywords: ['岩石', '尖岩', 'rock', 'spire'],
    icon: '🗻',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/rock_tall.glb', targetSize: 4.5 },
  },
  {
    id: 'building_bridge_stone_glb',
    category: 'building',
    label: '石橋',
    keywords: ['橋', '石橋', 'bridge', 'stone'],
    icon: '🌉',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/bridge_stone.glb', targetSize: 12 },
  },
  {
    id: 'building_tent_glb',
    category: 'building',
    label: '帳篷',
    keywords: ['帳篷', '帳', 'tent'],
    icon: '⛺',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-survival/tent.glb', targetSize: 6 },
  },
  {
    id: 'vehicle_sailboat_glb',
    category: 'vehicle',
    label: '帆船',
    keywords: ['船', '帆船', 'boat', 'sail'],
    icon: '⛵',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-watercraft/boat-sail.glb', targetSize: 8 },
  },
  {
    id: 'vehicle_canoe_glb',
    category: 'vehicle',
    label: '獨木舟',
    keywords: ['獨木舟', '船', 'canoe'],
    icon: '🛶',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/canoe.glb', targetSize: 5.5 },
  },
  {
    id: 'religious_cross_glb',
    category: 'religious_mythical',
    label: '十字架',
    keywords: ['十字架', '十字', 'cross'],
    icon: '✝️',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/cross.glb', targetSize: 3.5 },
  },
  {
    id: 'religious_candle_glb',
    category: 'religious_mythical',
    label: '蠟燭',
    keywords: ['蠟燭', '燭', 'candle'],
    icon: '🕯️',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/candle.glb', targetSize: 1.8 },
  },
  {
    id: 'religious_altar_glb',
    category: 'religious_mythical',
    label: '石祭壇',
    keywords: ['祭壇', '石祭壇', 'altar'],
    icon: '⛩️',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/altar-stone.glb', targetSize: 4 },
  },
  {
    id: 'fantasy_ghost_glb',
    category: 'fantasy',
    label: '幽靈',
    keywords: ['幽靈', '鬼', 'ghost'],
    icon: '👻',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/character-ghost.glb', targetSize: 3.5 },
  },
  {
    id: 'fantasy_skeleton_glb',
    category: 'fantasy',
    label: '骷髏',
    keywords: ['骷髏', '骨骸', 'skeleton'],
    icon: '💀',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/character-skeleton.glb', targetSize: 4 },
  },
  {
    id: 'fantasy_orc_glb',
    category: 'fantasy',
    label: '半獸人',
    keywords: ['半獸人', '獸人', 'orc'],
    icon: '👹',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-mini-dungeon/character-orc.glb', targetSize: 4 },
  },

  // 人物（第二批）
  {
    id: 'person_male_b_glb',
    category: 'person',
    label: '西裝一',
    keywords: ['男人', '男性', 'man'],
    icon: '👨‍🦱',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/man-suit.glb', targetSize: 4.5 },
  },
  {
    id: 'person_female_b_glb',
    category: 'person',
    label: '正裝',
    keywords: ['女人', '女性', 'woman'],
    icon: '👩‍🦰',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/woman-formal.glb', targetSize: 4.5 },
  },
  {
    id: 'person_wheelchair_glb',
    category: 'person',
    label: '輪椅',
    keywords: ['輪椅', 'wheelchair'],
    icon: '🦽',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-mini-characters/wheelchair.glb', targetSize: 3.5 },
  },

  // 動物（第二批）
  {
    id: 'animal_cow_glb',
    category: 'animal_land',
    label: '乳牛',
    keywords: ['牛', '乳牛', 'cow'],
    icon: '🐄',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/cow.glb', targetSize: 5 },
  },
  {
    id: 'animal_alpaca_glb',
    category: 'animal_land',
    label: '羊駝',
    keywords: ['羊駝', '草泥馬', 'alpaca'],
    icon: '🦙',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/alpaca.glb', targetSize: 4 },
  },
  {
    id: 'animal_donkey_glb',
    category: 'animal_land',
    label: '驢子',
    keywords: ['驢', '驢子', 'donkey'],
    icon: '🫏',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/donkey.glb', targetSize: 4.5 },
  },
  {
    id: 'animal_stag_glb',
    category: 'animal_land',
    label: '雄鹿',
    keywords: ['鹿', '雄鹿', 'stag'],
    icon: '🦌',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/stag.glb', targetSize: 4.8 },
  },

  // 植物（第二批）
  {
    id: 'plant_palm_glb',
    category: 'plant',
    label: '棕櫚樹',
    keywords: ['棕櫚', '椰子樹', 'palm'],
    icon: '🌴',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/tree_palm.glb', targetSize: 9 },
  },
  {
    id: 'plant_bush_glb',
    category: 'plant',
    label: '灌木',
    keywords: ['灌木', '樹叢', 'bush'],
    icon: '🌿',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/plant_bush.glb', targetSize: 3 },
  },

  // 自然物（第二批）
  {
    id: 'natural_campfire_glb',
    category: 'natural',
    label: '石圈火堆',
    keywords: ['營火', '火堆', '火', 'campfire', 'fire'],
    icon: '🔥',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/campfire_stones.glb', targetSize: 3.5 },
  },
  {
    id: 'natural_mountain_glb',
    category: 'natural',
    label: '山',
    keywords: ['山', '高山', 'mountain'],
    icon: '⛰️',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-fantasy-rts/mountain.gltf', targetSize: 14 },
  },

  // 建築（第二批）
  {
    id: 'building_fantasy_house_glb',
    category: 'building',
    label: '小屋',
    keywords: ['小屋', '房屋', '茅屋', 'house', 'hut'],
    icon: '🛖',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-fantasy-rts/house.gltf', targetSize: 8 },
  },
  {
    id: 'building_fence_glb',
    category: 'building',
    label: '圍籬',
    keywords: ['圍籬', '柵欄', '籬笆', 'fence'],
    icon: '🚧',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/fence_simple.glb', targetSize: 6 },
  },

  // 交通工具（第二批）
  {
    id: 'vehicle_sedan_glb',
    category: 'vehicle',
    label: '轎車',
    keywords: ['轎車', '汽車', '車', 'car', 'sedan'],
    icon: '🚙',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-car-kit/sedan.glb', targetSize: 5 },
  },
  {
    id: 'vehicle_ambulance_glb',
    category: 'vehicle',
    label: '救護車',
    keywords: ['救護車', 'ambulance'],
    icon: '🚑',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-car-kit/ambulance.glb', targetSize: 5.5 },
  },
  {
    id: 'vehicle_rowboat_glb',
    category: 'vehicle',
    label: '划艇',
    keywords: ['划艇', '小船', 'rowboat'],
    icon: '🚣',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-watercraft/boat-row-small.glb', targetSize: 5 },
  },

  // 宗教／神話（第二批）
  {
    id: 'religious_gravestone_glb',
    category: 'religious_mythical',
    label: '墓碑',
    keywords: ['墓碑', '墓', 'gravestone', 'grave'],
    icon: '🪦',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/gravestone-round.glb', targetSize: 2.5 },
  },
  {
    id: 'religious_obelisk_glb',
    category: 'religious_mythical',
    label: '方尖碑',
    keywords: ['方尖碑', '石柱', 'obelisk'],
    icon: '🗿',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/pillar-obelisk.glb', targetSize: 4 },
  },
  {
    id: 'religious_lantern_glb',
    category: 'religious_mythical',
    label: '燈籠',
    keywords: ['燈籠', '燈', 'lantern'],
    icon: '🏮',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/lantern-candle.glb', targetSize: 2 },
  },

  // 幻想生物（第二批）
  {
    id: 'fantasy_vampire_glb',
    category: 'fantasy',
    label: '吸血鬼',
    keywords: ['吸血鬼', 'vampire'],
    icon: '🧛',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/character-vampire.glb', targetSize: 4 },
  },
  {
    id: 'fantasy_zombie_glb',
    category: 'fantasy',
    label: '殭屍',
    keywords: ['殭屍', '喪屍', 'zombie'],
    icon: '🧟',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/character-zombie.glb', targetSize: 4 },
  },

  // ────────────────────────────────────────────────────────────
  // 水中動物（Quaternius Animated Fish Pack / Cute Fish Pack，OBJ 轉 GLB）
  // ────────────────────────────────────────────────────────────
  {
    id: 'animal_whale_glb',
    category: 'animal_water',
    label: '鯨魚',
    keywords: ['鯨魚', '鯨', '海洋', '水中', 'whale'],
    icon: '🐋',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-sea/whale.glb', targetSize: 9 },
  },
  {
    id: 'animal_dolphin_glb',
    category: 'animal_water',
    label: '海豚',
    keywords: ['海豚', '海洋', '水中', 'dolphin'],
    icon: '🐬',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-sea/dolphin.glb', targetSize: 5 },
  },
  {
    id: 'animal_shark_glb',
    category: 'animal_water',
    label: '鯊魚',
    keywords: ['鯊魚', '鯊', '海洋', '水中', 'shark'],
    icon: '🦈',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-sea/shark.glb', targetSize: 5.5 },
  },
  {
    id: 'animal_manta_glb',
    category: 'animal_water',
    label: '魟魚',
    keywords: ['魟魚', '魟', '海洋', '水中', 'manta', 'ray'],
    icon: '🐟',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-sea/manta.glb', targetSize: 4.5 },
  },
  {
    id: 'animal_koi_glb',
    category: 'animal_water',
    label: '錦鯉',
    keywords: ['錦鯉', '鯉魚', '魚', '水中', 'koi'],
    icon: '🎏',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-sea/koi.glb', targetSize: 2.5 },
  },
  {
    id: 'animal_clownfish_glb',
    category: 'animal_water',
    label: '小丑魚',
    keywords: ['小丑魚', '魚', '水中', 'clownfish'],
    icon: '🐠',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-sea/clownfish.glb', targetSize: 1.8 },
  },
  {
    id: 'animal_goldfish_glb',
    category: 'animal_water',
    label: '金魚',
    keywords: ['金魚', '魚', '水中', 'goldfish'],
    icon: '🐡',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-sea/goldfish.glb', targetSize: 1.8 },
  },

  // 陸地動物（第三批）
  {
    id: 'animal_pig_glb',
    category: 'animal_land',
    label: '豬',
    keywords: ['豬', 'pig'],
    icon: '🐷',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-farm/pig.glb', targetSize: 3.5 },
  },
  {
    id: 'animal_sheep_glb',
    category: 'animal_land',
    label: '綿羊',
    keywords: ['綿羊', '羊', 'sheep'],
    icon: '🐑',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-farm/sheep.glb', targetSize: 3.5 },
  },
  {
    id: 'animal_zebra_glb',
    category: 'animal_land',
    label: '斑馬',
    keywords: ['斑馬', 'zebra'],
    icon: '🦓',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-farm/zebra.glb', targetSize: 5 },
  },
  {
    id: 'animal_shiba_glb',
    category: 'animal_land',
    label: '柴犬',
    keywords: ['柴犬', '狗', 'shiba', 'dog'],
    icon: '🐕‍🦺',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/shiba.glb', targetSize: 3 },
  },
  {
    id: 'animal_bull_glb',
    category: 'animal_land',
    label: '公牛',
    keywords: ['公牛', '牛', 'bull'],
    icon: '🐂',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/bull.glb', targetSize: 5.5 },
  },

  // 寶物（沙遊中常見的珍寶／秘密象徵）
  {
    id: 'fantasy_treasure_glb',
    category: 'fantasy',
    label: '寶箱',
    keywords: ['寶箱', '寶藏', '寶物', 'treasure', 'chest'],
    icon: '🧰',
    visualSource: { type: 'gltf', url: 'assets/models/pirate-kit/treasure-chest.gltf', targetSize: 3 },
  },

  // ────────────────────────────────────────────────────────────
  // 擴充批次：更多人物原型、器物、交通工具（Quaternius / Kenney，CC0）
  // ────────────────────────────────────────────────────────────
  {
    id: 'person_farmer_glb',
    category: 'person',
    label: '農夫',
    keywords: ['農夫', '農人', 'farmer'],
    icon: '👨‍🌾',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/farmer.glb', targetSize: 4.5 },
  },
  {
    id: 'person_worker_glb',
    category: 'person',
    label: '工人一',
    keywords: ['工人', 'worker'],
    icon: '👷',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/worker.glb', targetSize: 4.5 },
  },
  {
    id: 'person_adventurer_glb',
    category: 'person',
    label: '冒險者',
    keywords: ['冒險者', '探險家', 'adventurer'],
    icon: '🧗',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/adventurer.glb', targetSize: 4.5 },
  },
  {
    id: 'fantasy_king_glb',
    category: 'fantasy',
    label: '國王',
    keywords: ['國王', '王', 'king'],
    icon: '🤴',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/king.glb', targetSize: 4.8 },
  },
  {
    id: 'fantasy_witch_glb',
    category: 'fantasy',
    label: '女巫',
    keywords: ['女巫', '巫婆', 'witch'],
    icon: '🧙‍♀️',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/witch.glb', targetSize: 4.5 },
  },
  {
    id: 'fantasy_sword_glb',
    category: 'fantasy',
    label: '劍',
    keywords: ['劍', '武器', 'sword'],
    icon: '🗡️',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-rpg/sword.glb', targetSize: 3 },
  },
  {
    id: 'fantasy_crown_glb',
    category: 'fantasy',
    label: '皇冠',
    keywords: ['皇冠', '王冠', 'crown'],
    icon: '👑',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-rpg/crown.glb', targetSize: 2 },
  },
  {
    id: 'religious_book_glb',
    category: 'religious_mythical',
    label: '書本',
    keywords: ['書', '書本', '典籍', 'book'],
    icon: '📖',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-rpg/book.glb', targetSize: 2 },
  },
  {
    id: 'vehicle_train_glb',
    category: 'vehicle',
    label: '火車頭',
    keywords: ['火車', '火車頭', 'train', 'locomotive'],
    icon: '🚂',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-train/locomotive.glb', targetSize: 6 },
  },
  {
    id: 'fantasy_snowman_glb',
    category: 'fantasy',
    label: '雪人',
    keywords: ['雪人', 'snowman'],
    icon: '⛄',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-holiday/snowman.glb', targetSize: 3.5 },
  },
  {
    id: 'building_bench_glb',
    category: 'building',
    label: '長椅',
    keywords: ['長椅', '椅子', 'bench'],
    icon: '🪑',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/bench.glb', targetSize: 3.5 },
  },

  // ────────────────────────────────────────────────────────────
  // 大批擴充：讓物件庫更接近實體沙遊收藏的廣度（Kenney / Quaternius，CC0）
  // ────────────────────────────────────────────────────────────
  {
    id: 'person_hoodie_glb',
    category: 'person',
    label: '連帽青年',
    keywords: ['連帽', '男孩', '青少年', 'hoodie'],
    icon: '🧑',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/hoodie-man.glb', targetSize: 4.5 },
  },
  {
    id: 'person_punk_glb',
    category: 'person',
    label: '龐克青年',
    keywords: ['龐克', '青年', 'punk'],
    icon: '🧑‍🎤',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/punk-man.glb', targetSize: 4.5 },
  },
  {
    id: 'person_beach_glb',
    category: 'person',
    label: '泳客',
    keywords: ['泳裝', '海灘', 'beach'],
    icon: '🏖️',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/beach-man.glb', targetSize: 4.5 },
  },
  {
    id: 'person_medieval_glb',
    category: 'person',
    label: '古裝',
    keywords: ['古裝', '中世紀', 'medieval'],
    icon: '👸',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/medieval-woman.glb', targetSize: 4.5 },
  },
  {
    id: 'person_soldier_glb',
    category: 'person',
    label: '軍人',
    keywords: ['軍人', '士兵', 'soldier'],
    icon: '🪖',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/soldier-woman.glb', targetSize: 4.5 },
  },
  {
    id: 'person_suit_woman_glb',
    category: 'person',
    label: '西裝二',
    keywords: ['西裝', '女人', 'suit'],
    icon: '🕴️',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/suit-woman.glb', targetSize: 4.5 },
  },
  {
    id: 'person_worker_woman_glb',
    category: 'person',
    label: '工人二',
    keywords: ['工人', '女人', 'worker'],
    icon: '👷‍♀️',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/worker-woman.glb', targetSize: 4.5 },
  },
  {
    id: 'animal_horse_white_glb',
    category: 'animal_land',
    label: '白馬',
    keywords: ['白馬', '馬', 'white', 'horse'],
    icon: '🐎',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-animals/horse-white.glb', targetSize: 5.5 },
  },
  {
    id: 'animal_pug_glb',
    category: 'animal_land',
    label: '哈巴狗',
    keywords: ['哈巴狗', '狗', 'pug', 'dog'],
    icon: '🐶',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-farm/pug.glb', targetSize: 2.5 },
  },
  {
    id: 'animal_llama_glb',
    category: 'animal_land',
    label: '駱馬',
    keywords: ['駱馬', 'llama'],
    icon: '🦙',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-farm/llama.glb', targetSize: 4.2 },
  },
  {
    id: 'animal_betta_glb',
    category: 'animal_water',
    label: '鬥魚',
    keywords: ['鬥魚', '魚', '水中', 'betta'],
    icon: '🐟',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-sea/betta.glb', targetSize: 2 },
  },
  {
    id: 'animal_puffer_glb',
    category: 'animal_water',
    label: '河豚',
    keywords: ['河豚', '魚', '水中', 'puffer'],
    icon: '🐡',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-sea/puffer.glb', targetSize: 2.2 },
  },
  {
    id: 'animal_swordfish_glb',
    category: 'animal_water',
    label: '旗魚',
    keywords: ['旗魚', '魚', '水中', 'swordfish'],
    icon: '🐟',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-sea/swordfish.glb', targetSize: 4 },
  },
  {
    id: 'animal_piranha_glb',
    category: 'animal_water',
    label: '食人魚',
    keywords: ['食人魚', '魚', '水中', 'piranha'],
    icon: '🐟',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-sea/piranha.glb', targetSize: 2 },
  },
  {
    id: 'plant_tree_green_glb',
    category: 'plant',
    label: '綠樹',
    keywords: ['綠樹', '樹', 'tree'],
    icon: '🌳',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/tree_default.glb', targetSize: 7 },
  },
  {
    id: 'plant_tree_fall_glb',
    category: 'plant',
    label: '秋樹',
    keywords: ['秋樹', '楓', '紅葉', 'fall', 'autumn'],
    icon: '🍁',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/tree_default_fall.glb', targetSize: 7 },
  },
  {
    id: 'plant_tree_dark_glb',
    category: 'plant',
    label: '深綠樹',
    keywords: ['深綠樹', '樹', 'dark'],
    icon: '🌲',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/tree_default_dark.glb', targetSize: 7 },
  },
  {
    id: 'plant_pine_tall_glb',
    category: 'plant',
    label: '高松',
    keywords: ['高松', '松樹', 'pine'],
    icon: '🌲',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/tree_pineTallA.glb', targetSize: 9 },
  },
  {
    id: 'plant_tree_thin_glb',
    category: 'plant',
    label: '細樹',
    keywords: ['細樹', '樹', 'thin'],
    icon: '🌳',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/tree_thin.glb', targetSize: 7 },
  },
  {
    id: 'plant_tree_fat_glb',
    category: 'plant',
    label: '圓樹',
    keywords: ['圓樹', '樹', 'fat'],
    icon: '🌳',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/tree_fat.glb', targetSize: 6.5 },
  },
  {
    id: 'plant_flower_purple_glb',
    category: 'plant',
    label: '紫花',
    keywords: ['紫花', '花', 'purple'],
    icon: '💜',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/flower_purpleA.glb', targetSize: 2.5 },
  },
  {
    id: 'plant_flower_yellow_glb',
    category: 'plant',
    label: '黃花',
    keywords: ['黃花', '花', 'yellow'],
    icon: '💛',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/flower_yellowA.glb', targetSize: 2.5 },
  },
  {
    id: 'plant_grass_glb',
    category: 'plant',
    label: '草叢',
    keywords: ['草叢', '草', 'grass'],
    icon: '🌾',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/grass_large.glb', targetSize: 2.5 },
  },
  {
    id: 'plant_mushroom_tan_glb',
    category: 'plant',
    label: '褐蘑菇',
    keywords: ['褐蘑菇', '蘑菇', 'mushroom'],
    icon: '🍄‍🟫',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/mushroom_tan.glb', targetSize: 2 },
  },
  {
    id: 'plant_bush_large_glb',
    category: 'plant',
    label: '大灌木',
    keywords: ['大灌木', '灌木', 'bush'],
    icon: '🌿',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/plant_bushLarge.glb', targetSize: 4 },
  },
  {
    id: 'natural_rock_small_glb',
    category: 'natural',
    label: '小岩石',
    keywords: ['小岩石', '岩石', 'rock'],
    icon: '🪨',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/rock_smallA.glb', targetSize: 3 },
  },
  {
    id: 'building_gate_glb',
    category: 'building',
    label: '城門',
    keywords: ['城門', '城堡', 'gate', 'castle'],
    icon: '🏰',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-castle/gate.glb', targetSize: 8 },
  },
  {
    id: 'building_house2_glb',
    category: 'building',
    label: '石板屋',
    keywords: ['石板屋', '房屋', '石屋', 'house'],
    icon: '🏡',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-fantasy-rts/house2.gltf', targetSize: 8 },
  },
  {
    id: 'building_mine_glb',
    category: 'building',
    label: '礦坑',
    keywords: ['礦坑', '洞穴', 'mine', 'cave'],
    icon: '⛏️',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-fantasy-rts/mine.gltf', targetSize: 8 },
  },
  {
    id: 'vehicle_police_glb',
    category: 'vehicle',
    label: '警車',
    keywords: ['警車', '警察', 'police'],
    icon: '🚓',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-car-kit/police.glb', targetSize: 5 },
  },
  {
    id: 'vehicle_firetruck_glb',
    category: 'vehicle',
    label: '消防車',
    keywords: ['消防車', 'fire', 'firetruck'],
    icon: '🚒',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-car-kit/firetruck.glb', targetSize: 5.5 },
  },
  {
    id: 'vehicle_taxi_glb',
    category: 'vehicle',
    label: '計程車',
    keywords: ['計程車', 'taxi'],
    icon: '🚕',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-car-kit/taxi.glb', targetSize: 5 },
  },
  {
    id: 'vehicle_tractor_glb',
    category: 'vehicle',
    label: '拖拉機',
    keywords: ['拖拉機', '農機', 'tractor'],
    icon: '🚜',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-car-kit/tractor.glb', targetSize: 5 },
  },
  {
    id: 'vehicle_fishing_boat_glb',
    category: 'vehicle',
    label: '漁船',
    keywords: ['漁船', '船', 'fishing', 'boat'],
    icon: '🎣',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-watercraft/boat-fishing-small.glb', targetSize: 6 },
  },
  {
    id: 'vehicle_ship_glb',
    category: 'vehicle',
    label: '大帆船',
    keywords: ['輪船', '船', 'ship'],
    icon: '🛳️',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-watercraft/ship-small.glb', targetSize: 7 },
  },
  {
    id: 'vehicle_pirate_ship_glb',
    category: 'vehicle',
    label: '海盜船',
    keywords: ['海盜船', '船', 'pirate', 'ship'],
    icon: '🏴‍☠️',
    visualSource: { type: 'gltf', url: 'assets/models/pirate-kit/pirate-ship.gltf', targetSize: 9 },
  },
  {
    id: 'religious_coffin_glb',
    category: 'religious_mythical',
    label: '棺材',
    keywords: ['棺材', '死亡', 'coffin'],
    icon: '⚰️',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/coffin.glb', targetSize: 5 },
  },
  {
    id: 'religious_gravestone_cross_glb',
    category: 'religious_mythical',
    label: '十字墓碑',
    keywords: ['十字墓碑', '墓碑', 'gravestone'],
    icon: '🪦',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/gravestone-cross.glb', targetSize: 3 },
  },
  {
    id: 'religious_urn_glb',
    category: 'religious_mythical',
    label: '陶罐',
    keywords: ['陶罐', '罐', 'urn'],
    icon: '🏺',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/urn-round.glb', targetSize: 2.5 },
  },
  {
    id: 'religious_firebasket_glb',
    category: 'religious_mythical',
    label: '火盆',
    keywords: ['火盆', '火', 'fire'],
    icon: '🔥',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-graveyard/fire-basket.glb', targetSize: 3 },
  },
  {
    id: 'fantasy_chest_wood_glb',
    category: 'fantasy',
    label: '木箱',
    keywords: ['木箱', '箱子', 'chest'],
    icon: '📦',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-rpg/chest-wood.glb', targetSize: 3 },
  },
  {
    id: 'fantasy_gem_glb',
    category: 'fantasy',
    label: '寶石',
    keywords: ['寶石', '水晶', 'gem', 'crystal'],
    icon: '💎',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-rpg/gem.glb', targetSize: 2 },
  },
  {
    id: 'fantasy_coin_glb',
    category: 'fantasy',
    label: '金幣',
    keywords: ['金幣', '錢', 'coin'],
    icon: '🪙',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-rpg/coin.glb', targetSize: 1.5 },
  },
  {
    id: 'fantasy_bow_glb',
    category: 'fantasy',
    label: '弓',
    keywords: ['弓', '武器', 'bow'],
    icon: '🏹',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-rpg/bow.glb', targetSize: 3.5 },
  },
  {
    id: 'fantasy_key_glb',
    category: 'fantasy',
    label: '鑰匙',
    keywords: ['鑰匙', 'key'],
    icon: '🗝️',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-rpg/key.glb', targetSize: 2 },
  },

  // 視角/物件擴充批次：火車車廂、更多植物、營火、更多人物
  {
    id: 'person_adventurer_m_glb',
    category: 'person',
    label: '探險家',
    keywords: ['探險家', '冒險', 'adventurer'],
    icon: '🧭',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/adventurer-man.glb', targetSize: 4.5 },
  },
  {
    id: 'person_astronaut_glb',
    category: 'person',
    label: '太空人',
    keywords: ['太空人', '宇航員', 'astronaut', 'space'],
    icon: '🧑‍🚀',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/astronaut.glb', targetSize: 4.5 },
  },
  {
    id: 'person_swat_glb',
    category: 'person',
    label: '特警',
    keywords: ['特警', '警察', 'swat', 'police'],
    icon: '🚔',
    visualSource: { type: 'gltf', url: 'assets/models/quaternius-people/swat.glb', targetSize: 4.5 },
  },
  {
    id: 'vehicle_carriage_box_glb',
    category: 'vehicle',
    label: '貨運車廂',
    keywords: ['火車', '車廂', '貨運', 'train', 'carriage'],
    icon: '🚃',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-train/train-carriage-box.glb', targetSize: 5.5 },
  },
  {
    id: 'vehicle_carriage_coal_glb',
    category: 'vehicle',
    label: '煤炭車廂',
    keywords: ['火車', '車廂', '煤炭', 'train', 'coal'],
    icon: '🚃',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-train/train-carriage-coal.glb', targetSize: 5.5 },
  },
  {
    id: 'vehicle_carriage_passenger_glb',
    category: 'vehicle',
    label: '客運車廂',
    keywords: ['火車', '車廂', '客運', 'train', 'passenger'],
    icon: '🚋',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-train/train-locomotive-passenger-a.glb', targetSize: 6 },
  },
  {
    id: 'plant_cactus_glb',
    category: 'plant',
    label: '仙人掌',
    keywords: ['仙人掌', '沙漠', 'cactus'],
    icon: '🌵',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/cactus_short.glb', targetSize: 3 },
  },
  {
    id: 'plant_cactus_tall_glb',
    category: 'plant',
    label: '高仙人掌',
    keywords: ['仙人掌', '沙漠', 'cactus'],
    icon: '🌵',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/cactus_tall.glb', targetSize: 4.5 },
  },
  {
    id: 'plant_lily_glb',
    category: 'natural',
    label: '睡蓮',
    keywords: ['睡蓮', '蓮花', '水', 'lily', 'lotus'],
    icon: '🪷',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/lily_large.glb', targetSize: 2.5 },
  },
  {
    id: 'plant_tree_simple_glb',
    category: 'plant',
    label: '小綠樹',
    keywords: ['小綠樹', '樹', 'tree'],
    icon: '🌳',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/tree_simple.glb', targetSize: 6 },
  },
  {
    id: 'plant_tree_tall_glb',
    category: 'plant',
    label: '高樹',
    keywords: ['高樹', '樹', 'tree'],
    icon: '🌳',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/tree_tall.glb', targetSize: 8.5 },
  },
  {
    id: 'plant_tree_cone_glb',
    category: 'plant',
    label: '圓錐樹',
    keywords: ['圓錐樹', '樹', 'cone'],
    icon: '🌲',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/tree_cone.glb', targetSize: 7 },
  },
  {
    id: 'plant_tree_plateau_glb',
    category: 'plant',
    label: '平頂樹',
    keywords: ['平頂樹', '樹', '非洲', 'plateau'],
    icon: '🌳',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/tree_plateau.glb', targetSize: 6.5 },
  },
  {
    id: 'plant_oak_fall_glb',
    category: 'plant',
    label: '秋橡樹',
    keywords: ['秋橡樹', '橡樹', '紅葉', 'oak', 'fall'],
    icon: '🍂',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/tree_oak_fall.glb', targetSize: 8 },
  },
  {
    id: 'plant_palm_short_glb',
    category: 'plant',
    label: '矮棕櫚',
    keywords: ['矮棕櫚', '棕櫚', 'palm'],
    icon: '🌴',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/tree_palmShort.glb', targetSize: 6 },
  },
  {
    id: 'natural_stump_glb',
    category: 'natural',
    label: '樹樁',
    keywords: ['樹樁', '樹幹', 'stump'],
    icon: '🪵',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/stump_round.glb', targetSize: 2.5 },
  },
  {
    id: 'natural_log_glb',
    category: 'natural',
    label: '圓木',
    keywords: ['圓木', '木頭', 'log'],
    icon: '🪵',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/log.glb', targetSize: 4 },
  },
  {
    id: 'plant_grass_small_glb',
    category: 'plant',
    label: '小草',
    keywords: ['小草', '草', 'grass'],
    icon: '🌱',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-nature/grass_leafs.glb', targetSize: 2 },
  },
  {
    id: 'natural_campfire_pit_glb',
    category: 'natural',
    label: '營火坑',
    keywords: ['營火坑', '火坑', 'campfire'],
    icon: '🕳️',
    visualSource: { type: 'gltf', url: 'assets/models/kenney-survival/campfire-pit.glb', targetSize: 3.5 },
  },
  {
    id: 'natural_campfire_burning',
    category: 'natural',
    label: '營火',
    keywords: ['營火', '火', '火堆', 'campfire', 'fire'],
    icon: '🔥',
    visualSource: { type: 'procedural', builderKey: 'burningCampfire' },
  },
];
